export const produtosIniciaisAlimentos = [
  { jaPegou: false, qte: 0, produto: "Arroz", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Açúcar cristal", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Açúcar refinado", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Feijão", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sal", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Farinha de trigo", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Farinha de mandioca", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Fubá", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Café", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Macarrão", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Milho de Pipoca", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Nescau ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Coco ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Maizena ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Biscoito ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sucrilios ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Tempero para salada ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Suco ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Knor ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Leite de coco ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Leite condensado ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Creme de leite ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Oleo ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Azeite ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Extrato de tomate ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Atum ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Ervilha ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Milho verde ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Molho inglês ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Molho de pimenta ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Cat chup ", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Maionese", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Alho", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Cebola", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Azeitona", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Gordura hidrogenada", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Margarina", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Peito de Frango", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Batata palha", preco: 0 },
];

export const produtosIniciaisLimpeza = [
  { jaPegou: false, qte: 0, produto: "Toalha de papel", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Palito", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Fósforo", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Álcool", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Água sanitária", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sapolio", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Detergente", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sabão em pó", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sabão em barra", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Amaciante", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Bombril", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Pasta de dente", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Papel higiênico", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Sabonete", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Shampo", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Absorvente", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Barbeador", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Cotonete", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Bucha", preco: 0 },
  { jaPegou: false, qte: 0, produto: "Pedra Sanitária", preco: 0 },
];
